source 'https://github.com/CocoaPods/Specs.git'

target 'XScroll', :exclusive => true do
  pod "ASOXScrollTableViewCell", :path => "../ASOXScrollTableViewCell.podspec"
end

target 'XScrollTests', :exclusive => true do
  pod "ASOXScrollTableViewCell", :path => "../ASOXScrollTableViewCell.podspec"
end
